package com.wishfulcloud.dataServ.admin.entity;

import java.io.Serializable;
import java.util.Date;

import org.hibernate.validator.constraints.NotBlank;

/**
 * Model class of 菜单表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Menu implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 编号. */
	private String id;

	/** 父级id. */
	@NotBlank(message = "父级id不能为空")
	private String parentId;

	/** 租户编号. */
	@NotBlank(message = "租户编号不能为空")
	private String tenantCode;

	/** 菜单名称. */
	@NotBlank(message = "菜单名称不能为空")
	private String menuName;

	/** 链接. */
	private String href;

	/** 目标. */
	private String target;

	/** 图标. */
	private String icon;

	/** 是否在菜单中显示. */
	@NotBlank(message = "是否在菜单中显示不能为空")
	private String isShow;

	/** 权限标识. */
	private String permission;

	/** 排序. */
	private Integer sort;

	/** 创建时间. */
	private Date createDate = new Date();

	/** 更新时间. */
	private Date updateDate = new Date();

	/** 备注信息. */
	private String remarks = " ";

	/** 删除标记. */
	private String delFlag = "0";

	/**
	 * Constructor.
	 */
	public Menu() {
	}

	/**
	 * Set the 编号.
	 * 
	 * @param id
	 *            编号
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 编号.
	 * 
	 * @return 编号
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 父级id.
	 * 
	 * @param parentId
	 *            父级id
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * Get the 父级id.
	 * 
	 * @return 父级id
	 */
	public String getParentId() {
		return this.parentId;
	}

	/**
	 * Set the 租户编号.
	 * 
	 * @param tenantCode
	 *            租户编号
	 */
	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	/**
	 * Get the 租户编号.
	 * 
	 * @return 租户编号
	 */
	public String getTenantCode() {
		return this.tenantCode;
	}

	/**
	 * Set the 菜单名称.
	 * 
	 * @param menuName
	 *            菜单名称
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	/**
	 * Get the 菜单名称.
	 * 
	 * @return 菜单名称
	 */
	public String getMenuName() {
		return this.menuName;
	}

	/**
	 * Set the 链接.
	 * 
	 * @param href
	 *            链接
	 */
	public void setHref(String href) {
		this.href = href;
	}

	/**
	 * Get the 链接.
	 * 
	 * @return 链接
	 */
	public String getHref() {
		return this.href;
	}

	/**
	 * Set the 目标.
	 * 
	 * @param target
	 *            目标
	 */
	public void setTarget(String target) {
		this.target = target;
	}

	/**
	 * Get the 目标.
	 * 
	 * @return 目标
	 */
	public String getTarget() {
		return this.target;
	}

	/**
	 * Set the 图标.
	 * 
	 * @param icon
	 *            图标
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * Get the 图标.
	 * 
	 * @return 图标
	 */
	public String getIcon() {
		return this.icon;
	}

	/**
	 * Set the 是否在菜单中显示.
	 * 
	 * @param isShow
	 *            是否在菜单中显示
	 */
	public void setIsShow(String isShow) {
		this.isShow = isShow;
	}

	/**
	 * Get the 是否在菜单中显示.
	 * 
	 * @return 是否在菜单中显示
	 */
	public String getIsShow() {
		return this.isShow;
	}

	/**
	 * Set the 权限标识.
	 * 
	 * @param permission
	 *            权限标识
	 */
	public void setPermission(String permission) {
		this.permission = permission;
	}

	/**
	 * Get the 权限标识.
	 * 
	 * @return 权限标识
	 */
	public String getPermission() {
		return this.permission;
	}

	/**
	 * Set the 排序.
	 * 
	 * @param sort
	 *            排序
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * Get the 排序.
	 * 
	 * @return 排序
	 */
	public Integer getSort() {
		return this.sort;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Menu other = (Menu) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
