package com.wishfulcloud.dataServ.admin.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 角色表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Role implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 编号. */
	private String id;

	/** 租户编号. */
	private String tenantCode;

	/** 归属机构. */
	private String groupId;

	/** 角色名称. */
	private String roleName;

	/** 英文名称. */
	private String enname;

	/** 角色类型. */
	private String roleType;

	/** 数据范围. */
	private String dataScope;

	/** 是否系统数据. */
	private String isSys;

	/** 是否可用. */
	private String useable;

	/** 创建时间. */
	private Date createDate;

	/** 更新时间. */
	private Date updateDate;

	/** 备注信息. */
	private String remarks;

	/** 删除标记. */
	private String delFlag;

	/**
	 * Constructor.
	 */
	public Role() {
	}

	/**
	 * Set the 编号.
	 * 
	 * @param id
	 *            编号
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 编号.
	 * 
	 * @return 编号
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 租户编号.
	 * 
	 * @param tenantCode
	 *            租户编号
	 */
	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	/**
	 * Get the 租户编号.
	 * 
	 * @return 租户编号
	 */
	public String getTenantCode() {
		return this.tenantCode;
	}

	/**
	 * Set the 归属机构.
	 * 
	 * @param groupId
	 *            归属机构
	 */
	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	/**
	 * Get the 归属机构.
	 * 
	 * @return 归属机构
	 */
	public String getGroupId() {
		return this.groupId;
	}

	/**
	 * Set the 角色名称.
	 * 
	 * @param roleName
	 *            角色名称
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * Get the 角色名称.
	 * 
	 * @return 角色名称
	 */
	public String getRoleName() {
		return this.roleName;
	}

	/**
	 * Set the 英文名称.
	 * 
	 * @param enname
	 *            英文名称
	 */
	public void setEnname(String enname) {
		this.enname = enname;
	}

	/**
	 * Get the 英文名称.
	 * 
	 * @return 英文名称
	 */
	public String getEnname() {
		return this.enname;
	}

	/**
	 * Set the 角色类型.
	 * 
	 * @param roleType
	 *            角色类型
	 */
	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	/**
	 * Get the 角色类型.
	 * 
	 * @return 角色类型
	 */
	public String getRoleType() {
		return this.roleType;
	}

	/**
	 * Set the 数据范围.
	 * 
	 * @param dataScope
	 *            数据范围
	 */
	public void setDataScope(String dataScope) {
		this.dataScope = dataScope;
	}

	/**
	 * Get the 数据范围.
	 * 
	 * @return 数据范围
	 */
	public String getDataScope() {
		return this.dataScope;
	}

	/**
	 * Set the 是否系统数据.
	 * 
	 * @param isSys
	 *            是否系统数据
	 */
	public void setIsSys(String isSys) {
		this.isSys = isSys;
	}

	/**
	 * Get the 是否系统数据.
	 * 
	 * @return 是否系统数据
	 */
	public String getIsSys() {
		return this.isSys;
	}

	/**
	 * Set the 是否可用.
	 * 
	 * @param useable
	 *            是否可用
	 */
	public void setUseable(String useable) {
		this.useable = useable;
	}

	/**
	 * Get the 是否可用.
	 * 
	 * @return 是否可用
	 */
	public String getUseable() {
		return this.useable;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Role other = (Role) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
