package com.wishfulcloud.dataServ.product.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 理财产品指标.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FinancingProductQuota implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private String id;

	/** 理财产品id. */
	private String productid;

	/** 总金额. */
	private Double totalMoney;

	/** 余额. */
	private Double balance;

	/** 成交次数. */
	private Integer dealTimes;

	/** 创建时间. */
	private Date createDate;

	/** 更新时间. */
	private Date updateDate;

	/** 备注信息. */
	private String remarks;

	/** 删除标记. */
	private String delFlag;

	/**
	 * Constructor.
	 */
	public FinancingProductQuota() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 理财产品id.
	 * 
	 * @param productid
	 *            理财产品id
	 */
	public void setProductid(String productid) {
		this.productid = productid;
	}

	/**
	 * Get the 理财产品id.
	 * 
	 * @return 理财产品id
	 */
	public String getProductid() {
		return this.productid;
	}

	/**
	 * Set the 总金额.
	 * 
	 * @param totalMoney
	 *            总金额
	 */
	public void setTotalMoney(Double totalMoney) {
		this.totalMoney = totalMoney;
	}

	/**
	 * Get the 总金额.
	 * 
	 * @return 总金额
	 */
	public Double getTotalMoney() {
		return this.totalMoney;
	}

	/**
	 * Set the 余额.
	 * 
	 * @param balance
	 *            余额
	 */
	public void setBalance(Double balance) {
		this.balance = balance;
	}

	/**
	 * Get the 余额.
	 * 
	 * @return 余额
	 */
	public Double getBalance() {
		return this.balance;
	}

	/**
	 * Set the 成交次数.
	 * 
	 * @param dealTimes
	 *            成交次数
	 */
	public void setDealTimes(Integer dealTimes) {
		this.dealTimes = dealTimes;
	}

	/**
	 * Get the 成交次数.
	 * 
	 * @return 成交次数
	 */
	public Integer getDealTimes() {
		return this.dealTimes;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FinancingProductQuota other = (FinancingProductQuota) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
