package com.wishfulcloud.dataServ.serialNum.entity;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

/**
 * Model class of 编号生成规则.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SerialNumberCreateRule implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 编号id. */
	private String id;

	/** 生成方式 : 0.自增长序号
	 * 			  1.时间戳
	 * 			  2.年度+序号
	 * 			  3.年度+月度+序号
	 * 			  4.年度+月度+日+序号
	 * 			  5.时间戳+序号
	 * 			  6.文本（传入）+序号
	 * */
	@NotNull (message = "生成方式不能为空")
	private Integer createType;

	/** 序号位数. */
	@NotNull (message = "序号位数不能为空")
	private Integer digitCapacity;

	/** 文本位置 : 0 无文本
	 * 			  1 最前
	 * 			  2 最后
	 * 			  3 第一段后
	 * 			  4 第二段后
	 *            5 第三段后 
	 **/
	@NotNull(message = "文本位置不能为空")
	private Integer textLocation;

	/** 固定文本. */
	@NotBlank(message = "固定文本不能为空")
	private String fixedText;

	/** 序号起点. */
	@NotNull(message = "序号起点不能为空")
	private Integer beginning;

	/** 创建时间. */
	private Date createDate = new Date();

	/** 更新时间. */
	private Date updateDate = new Date();

	/** 备注信息. */
	private String remarks  = "";

	/** 删除标记. */
	private String delFlag = "0";

	/**
	 * Constructor.
	 */
	public SerialNumberCreateRule() {
	}

	/**
	 * Set the 编号id.
	 * 
	 * @param id
	 *            编号id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 编号id.
	 * 
	 * @return 编号id
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 生成方式.
	 * 
	 * @param createType
	 *            生成方式
	 */
	public void setCreateType(Integer createType) {
		this.createType = createType;
	}

	/**
	 * Get the 生成方式.
	 * 
	 * @return 生成方式
	 */
	public Integer getCreateType() {
		return this.createType;
	}

	/**
	 * Set the 序号位数.
	 * 
	 * @param digitCapacity
	 *            序号位数
	 */
	public void setDigitCapacity(Integer digitCapacity) {
		this.digitCapacity = digitCapacity;
	}

	/**
	 * Get the 序号位数.
	 * 
	 * @return 序号位数
	 */
	public Integer getDigitCapacity() {
		return this.digitCapacity;
	}

	/**
	 * Set the 文本位置.
	 * 
	 * @param textLocation
	 *            文本位置
	 */
	public void setTextLocation(Integer textLocation) {
		this.textLocation = textLocation;
	}

	/**
	 * Get the 文本位置.
	 * 
	 * @return 文本位置
	 */
	public Integer getTextLocation() {
		return this.textLocation;
	}

	/**
	 * Set the 固定文本.
	 * 
	 * @param fixedText
	 *            固定文本
	 */
	public void setFixedText(String fixedText) {
		this.fixedText = fixedText;
	}

	/**
	 * Get the 固定文本.
	 * 
	 * @return 固定文本
	 */
	public String getFixedText() {
		return this.fixedText;
	}

	/**
	 * Set the 序号起点.
	 * 
	 * @param beginning
	 *            序号起点
	 */
	public void setBeginning(Integer beginning) {
		this.beginning = beginning;
	}

	/**
	 * Get the 序号起点.
	 * 
	 * @return 序号起点
	 */
	public Integer getBeginning() {
		return this.beginning;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SerialNumberCreateRule other = (SerialNumberCreateRule) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
