package com.wishfulcloud.dataServ.product.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 理财产品.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FinancingProduct implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private String id;

	/** 租户编号. */
	private String tenantCode;

	/** 序号. */
	private String serialNumber;

	/** 产品名称. */
	private String productName;

	/** 起投金额. */
	private Double investAmount;

	/** 收益率. */
	private Double rateReturn;

	/** 期限. */
	private Integer timeLimit;

	/** 单位. */
	private String unit;

	/** 状态. */
	private Byte status;

	/** 序号. */
	private Integer sort;

	/** 详情描述. */
	private String detail;

	/** 创建时间. */
	private Date createDate;

	/** 更新时间. */
	private Date updateDate;

	/** 备注信息. */
	private String remarks;

	/** 删除标记. */
	private String delFlag;

	/**
	 * Constructor.
	 */
	public FinancingProduct() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param id
	 *            主键
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 租户编号.
	 * 
	 * @param tenantCode
	 *            租户编号
	 */
	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	/**
	 * Get the 租户编号.
	 * 
	 * @return 租户编号
	 */
	public String getTenantCode() {
		return this.tenantCode;
	}

	/**
	 * Set the 序号.
	 * 
	 * @param serialNumber
	 *            序号
	 */
	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	/**
	 * Get the 序号.
	 * 
	 * @return 序号
	 */
	public String getSerialNumber() {
		return this.serialNumber;
	}

	/**
	 * Set the 产品名称.
	 * 
	 * @param productName
	 *            产品名称
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * Get the 产品名称.
	 * 
	 * @return 产品名称
	 */
	public String getProductName() {
		return this.productName;
	}

	/**
	 * Set the 起投金额.
	 * 
	 * @param investAmount
	 *            起投金额
	 */
	public void setInvestAmount(Double investAmount) {
		this.investAmount = investAmount;
	}

	/**
	 * Get the 起投金额.
	 * 
	 * @return 起投金额
	 */
	public Double getInvestAmount() {
		return this.investAmount;
	}

	/**
	 * Set the 收益率.
	 * 
	 * @param rateReturn
	 *            收益率
	 */
	public void setRateReturn(Double rateReturn) {
		this.rateReturn = rateReturn;
	}

	/**
	 * Get the 收益率.
	 * 
	 * @return 收益率
	 */
	public Double getRateReturn() {
		return this.rateReturn;
	}

	/**
	 * Set the 期限.
	 * 
	 * @param timeLimit
	 *            期限
	 */
	public void setTimeLimit(Integer timeLimit) {
		this.timeLimit = timeLimit;
	}

	/**
	 * Get the 期限.
	 * 
	 * @return 期限
	 */
	public Integer getTimeLimit() {
		return this.timeLimit;
	}

	/**
	 * Set the 单位.
	 * 
	 * @param unit
	 *            单位
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * Get the 单位.
	 * 
	 * @return 单位
	 */
	public String getUnit() {
		return this.unit;
	}

	/**
	 * Set the 状态.
	 * 
	 * @param status
	 *            状态
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * Get the 状态.
	 * 
	 * @return 状态
	 */
	public Byte getStatus() {
		return this.status;
	}

	/**
	 * Set the 序号.
	 * 
	 * @param sort
	 *            序号
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * Get the 序号.
	 * 
	 * @return 序号
	 */
	public Integer getSort() {
		return this.sort;
	}

	/**
	 * Set the 详情描述.
	 * 
	 * @param detail
	 *            详情描述
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * Get the 详情描述.
	 * 
	 * @return 详情描述
	 */
	public String getDetail() {
		return this.detail;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FinancingProduct other = (FinancingProduct) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
